baseURL = "https://rentadonutboard.com/"
languageCode = "en-us"
title = "Rent a Donut Board"
theme = "hugo-universal-theme"
defaultContentLanguage = "en"
summaryLength = 70
pluralizelisttitles = false

[markup.goldmark.renderer]
  unsafe = true

[services]
  [services.disqus]
    shortname = ""
  [services.googleAnalytics]
    id = "G-BTK2X6PL44"

[pagination]
  pagerSize = 10

[params]
  contact_email = "homesupplies800@gmail.com"
  contact_phone = "616-635-9461"
  author = "Rent A Donut Board"
  defaultDescription = "Rent our beautiful donut board for your next event in the Wyoming, MI area!"
  disabled_logo = false
  logo_text = "Prestige Donut Board Rentals"
  logo = "img/PrestigeDonutLogo.png"
  logo_small = "img/PrestigeDonutLogo.png"

  # --- Contact & Footer Info ---
  contact_url = "/#contact-section"
  copyright = "Copyright (c) 2025, Prestige Donut Board Rentals; all rights reserved."
  about_us = "<p>Providing fun and delicious donut displays for your special events!</p>"
  address = """"""

  # --- Top Bar Configuration ---
  [params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Message Us Through Email: homesupplies800@gmail.com</p>
      <p class="hidden-md hidden-lg"><a href="tel:616-635-9461" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:homesupplies800@gmail.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

  # --- Styling ---
  style = "default"
  dropdown_mouse_over = false

  # --- Date Formatting ---
  date_format = "January 2, 2006"

  # --- Disabled Features ---
  enableGoogleMaps = false
  formspree_action = ""
  contact_form_ajax = false
  enableRecaptchaInContactForm = false
  mainSections = []

  [params.carouselHomepage]
    enable = false
  [params.features]
    enable = false
  [params.testimonials]
    enable = false
  [params.see_more]
    enable = false
  [params.clients]
    enable = false
  [params.recent_posts]
    enable = false
  [params.footer.recent_posts]
    enable = false

  [params.widgets]
    categories = false
    tags = false
    search = false

# --- Hugo Built-in Settings ---
[permalinks]

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

# --- Menus ---
[[menu.topbar]]
  weight = 1
  name = "Phone"
  url = "tel:616-635-9461"
  pre = "<i class='fas fa-phone'></i>"

[[menu.topbar]]
  weight = 2
  name = "Email"
  url = "mailto:homesupplies800@gmail.com"
  pre = "<i class='fas fa-envelope'></i>"